name: CI/CD Pipeline

on:
  pull_request:
    branches: [main, develop]
    paths:
      - "src/**"
      - "tests/**"
      - "feature_store/**"
      - "prefect_flows.py"
      - ".github/workflows/**"
      - "pyproject.toml"
  push:
    branches: [main, develop]
    paths:
      - "src/**"
      - "tests/**"
      - "feature_store/**"
      - "prefect_flows.py"
      - ".github/workflows/**"
      - "pyproject.toml"

jobs:
  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync --frozen --group lint

      - name: Run Ruff linter
        run: uv run ruff check .

      - name: Run Ruff formatter check
        run: uv run ruff format --check .

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync --frozen --group test

      - name: Run pytest
        run: uv run pytest tests/ -v --cov=src --cov-report=xml --cov-report=term

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

  validate-feast:
    name: Validate Feast Feature Store
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Feast
        run: uv sync --frozen --group feast

      - name: Validate feature definitions
        run: |
          cd feature_store
          uv run feast plan

      - name: Test Feast registry (dry-run)
        run: |
          cd feature_store
          uv run feast --help
          uv run python -c "from feast import FeatureStore; fs = FeatureStore(repo_path='.'); print('Feature store loaded successfully')"

  validate-prefect:
    name: Validate Prefect Flows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync --frozen --group prefect

      - name: Validate Prefect flows syntax
        run: uv run python -c "from prefect_flows import ml_pipeline_flow; print('Prefect flows validated successfully')"
