name: Deploy Feature Store

on:
  push:
    branches: [main]
    paths:
      - "feature_store/**"
      - "data/processed/player_features.parquet"
  workflow_dispatch:

jobs:
  deploy-feast:
    name: Deploy Feast Feature Store
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Feast
        run: uv sync --frozen --group feast

      - name: Run feast apply
        run: |
          cd feature_store
          uv run feast apply

      - name: Verify deployment
        run: |
          cd feature_store
          uv run feast feature-views list
          uv run feast entities list

      - name: Archive Feast registry (GitHub Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: feast-registry-${{ github.sha }}
          path: feature_store/data/registry.db
          retention-days: 30
